### ISSUE TITLE
Build failed on Ubuntu 23.10

### ISSUE THREAD

**Issue by zkbitcoin** [kroma-network/tachyon#370]
first thanks for this very interesting project and latest commits which allows build to succeed

using following script (on Ubuntu 23.10 with Python 3.11.6 cuda version release 12.4)

#!/bin/bash

export TMP=/tmp
export USE_BAZEL_VERSION=6.5.0
export CC=/usr/bin/gcc-12
export CXX=/usr/bin/g++-12
export GCC_HOST_COMPILER_PATH=/usr/bin/gcc-12

bazel build --config linux --config cuda //...
bazel test --config linux //...

subset of tests succceeds

Executed 45 out of 67 tests: 22 tests pass and 45 fail locally.

failures begin at //tachyon/c/math/elliptic_curves/msm:msm_unittests                       FAILED in 0.0s

question is (before I step in code any further) is this environment supported ? or this is just WIP (work in progress)

**Comment by zkbitcoin** [comment]
there is an error in compiler before unitest, could be just that, investigating std gcc-12 issue.. gcc-10 had other issues on ubuntu linux, will let know , maybe a non issue

**Comment by chokobole** [comment]
Thanks for the report! Yeap if you have any trouble, let us know!

**Comment by zkbitcoin** [comment]
> Thanks for the report! Yeap if you have any trouble, let us know!

isolated to invalid ops exceptions (via dmesg) for instance (but basically SIGINT 4 in bazel and unit test fails) , errors are similar in other unit test so has to be something common

 groth16_unittes[937384] trap invalid opcode ip:5711e6177f3b sp:7fffe3ebae88 error:0 in groth16_unittests[5711e6127000+e2000]

**Comment by chokobole** [comment]
Oh I See. 

This is our development environment, though. Our team will figure out with Ubuntu 23.10!

```shell
> g++ --version
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

>  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Comment by ashjeong** [comment]
@zkbitcoin 
We have tested on your given environment of Ubuntu 23.10, Python 3.11.6, and gcc/++-12, but could not find out how to replicate your issue. From our recent testing, we have realized there was a separate problem in which only 4 tests fail if `--config dbg` is not included and have solved this issue with PR #374 and #376. We would appreciate it if you could provide us with some more information on your development environment.

As a side note, note that `bazel build --config linux --config cuda //…` builds all bazel targets with cuda, yet `bazel test --config linux //…` builds and tests all bazel targets without cuda, so the resulting test failures you experienced was not a byproduct of running cuda.

**Comment by zkbitcoin** [comment]
@ashjeong could be after all process type, it is in my case cat /proc/cpuinfo  | grep 'name'| uniq
model name	: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz

would yu know how to get more verbose or extra info beyind just trap error in var log (foudn out Error 0 is divide by 0 exception)

so console produces (right before test unit failure) but /msm_unittests/test.log does not have much useful info

would love to isolate to one test and ultimately offending line 

//tachyon/zk/plonk/layout:circuit_unittests                              PASSED in 0.0s
//tachyon/c/math/elliptic_curves/msm:msm_unittests                       FAILED in 0.5s
  /home/user/.cache/bazel/_bazel_amilkowski/ffb593387705653e3699865ec1948a63/execroot/kroma_network_tachyon/bazel-out/k8-dbg/testlogs/tachyon/c/math/elliptic_curves/msm/msm_unittests/test.log

**Comment by zkbitcoin** [comment]
update and very strange if I run tests as follows

bazel test -s  --test_filter=GoldilocksPrimeFieldTest.AdditiveOperators --config dbg --config linux //...

Executed 67 out of 67 tests: 67 tests pass.

could it be that bazel itself is at fault ? (with the specific combination of compiler python / env)

plus if I specified just one suite with  --test_filter=GoldilocksPrimeFieldTest.AdditiveOperators why did it trigger all tests ?

**Comment by zkbitcoin** [comment]
ran a single unit test bazel test --test_filter=AffinePointTest.Zero --config linux --test_output=all //...

isolated to first line in SetUp tachyon_bn254_g1_init() faulting 

class AffinePointTest : public testing::Test {
 public:
  void SetUp() override {
    tachyon_bn254_g1_init();

**Comment by zkbitcoin** [comment]
closed it cause I took a different sever ran build test on it with same gcc/bazel and it worked so its environmental, maybe I have lib corrupt etc,

thanks for taking look at this anyways
