### ISSUE TITLE
Support openmp on mac

### ISSUE THREAD

**Issue by chokobole** [kroma-network/tachyon#401]
### Issue type

Build/Install

### OS platform and distribution

macOS Sonoma

### Current behavior?

If I try to build tachyon with openmp on mac, it causes an error. 

```shell
clang++: error: unsupported option '-fopenmp'
```

### Expected Behavior?

It should be buildable.

### Standalone code or description to reproduce the issue

```shell
bazel test --//:has_openmp //...
```

**Comment by batzor** [comment]
Following [SO article](https://stackoverflow.com/questions/60005176/how-to-deal-with-clang-error-unsupported-option-fopenmp-on-travis), I confirmed `-fopenmp` works with llvm clang but not sure how it should be fixed in bazel build.
