### ISSUE TITLE
Change function signature `T Inverse()` to `std::optional<T> Inverse()`

### ISSUE THREAD

**Issue by chokobole** [kroma-network/tachyon#76]
### Issue type

Feature Request

### Current behavior?

Currently `Inverse()` method returns a inverse and panics if failed using `CHECK()`. But this isn't GPU interoperable code. So I suggest it to change it to return `std::optional<T>` when it failed.

### Expected Behavior?

Returns false if failed and true and populates the `out` parameter.

**Comment by saliaku** [comment]
hey i can take this up

**Comment by chokobole** [comment]
@saliaku Oh thanks :) That would be awesome! If you have any question on this, please feel free to ask us.

**Comment by saliaku** [comment]
can you tell me which files to work on so that it would be easier for me to work

**Comment by chokobole** [comment]
The `Inverse()` is located in https://github.com/kroma-network/tachyon/blob/c6c7f83af0637973aec65fdef7a20d987060f0da/tachyon/math/base/groups.h#L79-L86

My idea is to change the content as follows.

```c++
  // Inverse: a⁻¹
  template <
      typename G2 = G,
      std::enable_if_t<internal::SupportsInverseInPlace<G2>::value>* = nullptr>
  [[nodiscard]] constexpr bool Inverse(G* inverse) const {
    *inverse = *static_cast<const G*>(this);
    return inverse->InverseInPlace();    
  }
```

Then it turns out you need to change all the  `InverseInPlace()` correspondingly.

Then you need to change https://github.com/kroma-network/tachyon/blob/c6c7f83af0637973aec65fdef7a20d987060f0da/tachyon/math/finite_fields/prime_field.h#L244-L248

```c++
  constexpr bool InverseInPlace() {
     return value_.template MontgomeryInverse<Config::kModulusHasSpareBit>(
        Config::kModulus, Config::kMontgomeryR2, &value_);
  }
```

Then it continues to https://github.com/kroma-network/tachyon/blob/c6c7f83af0637973aec65fdef7a20d987060f0da/tachyon/math/base/big_int.h#L732-L805

Here there is a `CHECK()` code to cause this issue.

```c++
  template <bool ModulusHasSpareBit>
  constexpr bool MontgomeryInverse(const BigInt& modulus,
                                     const BigInt& r2, BigInt* inverse) const {
    // See https://github.com/kroma-network/tachyon/issues/76
    if (IsZero()) return false;

     // ...

    if (u.IsOne()) {
      *inverse = b;
    } else {
      *inverse = c;
    } 
    return true;   
  }
```

I think this is a just start and if you compile this with the change above, you'll face many compile error because of the changing return type of `Inverse()`. This is how you can start with.

**Comment by chokobole** [comment]
The trade-off is other than this `XXXInPlace()` returns the reference of caller so that you can chain calling another method based on this reference. But `InverseInPlace()` can't do this.

**Comment by chokobole** [comment]
Close since https://github.com/kroma-network/tachyon/pull/424 is merged.
